### ISSUE TITLE
Project not running in my system

### ISSUE THREAD

**Issue by bjain31** [kunaltyagi9/University-Management-System#1]
When running  project files in intellij, it shows- java: package net.proteanit.sql does not exist. Then I converted this project into an executable jar file and trying to run it in intellij but it shows invalid or corrupt jar file. I have also tried to install netbeans but it shows no jdk on my computer. I have jdk-15 in my computer. Please give the solution.

**Comment by bjain31** [comment]
When running  project files in intellij, it shows- java: package net.proteanit.sql does not exist. Then I converted this project into an executable jar file and trying to run it in intellij but it shows invalid or corrupt jar file. I have also tried to install netbeans but it shows no jdk on my computer. I have jdk-15 in my computer. Please give the solution.

**Comment by kunaltyagi9** [comment]
For this, You need to include a jar file which is rs2xml.jar. This package is inside this jar file and if you will not import this. It will not work
Hence including this package under the libraries section will resolve this issue

**Comment by kunaltyagi9** [comment]
Closing this issue, as it will fix this
