### ISSUE TITLE
Database is missing

### ISSUE THREAD

**Issue by SyedMuradAliShah** [kunaltyagi9/University-Management-System#2]
Hi Tyagi bro,

Can you please include the database?

It will waste a lot of my time If I create a database myself.

I will be thankful if saved my time.

**Comment by kunaltyagi9** [comment]
It hardly takes less than a minute to execute a mysql query and you can create your database within 5 minutes after executing all the MYSQL Queries.

**Comment by SyedMuradAliShah** [comment]
Please approve my pull request I have already contribute the database.
